### ISSUE TITLE
NO MODULE NAMED REQUEST

### ISSUE THREAD

**Issue by m0rfeo** [inc0d3/moodlescan#11]
Hi, thanks for your work, when i try to do any options on moodlescan.py i recive the following error, I undestand that can't find urllib:

Traceback (most recent call last):
  File "moodlescan.py", line 12, in <module>
    from urllib.request import Request, urlopen 
ImportError: No module named request

**Comment by inc0d3** [comment]
You are running Python 3 code on Python 2; the Python 2 urllib and urllib2 modules were merged into urllib.request. Use Python3
