### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by rafalzda** [inc0d3/moodlescan#3]
Hey, can you tell me how can I scan site with self signed certificate?
Thanks :)

`Ha ocurrido un error al conectarse con el objetivo : [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1076)
`

**Comment by inc0d3** [comment]
Hi, in the new version is added a "-k" option for ignore certificate (invalid or self signed certificates)

**Comment by rafalzda** [comment]
Thanks 😉
