### ISSUE TITLE
Moodlescan 0.6

### ISSUE THREAD

**Issue by cfollin** [inc0d3/moodlescan#5]
Al intentar usar la nueva version de Moodlescan me aparece el mensaje "Error to connect with the target. check url option". Esto me pasa tanto en kali linux como en windows. Que puede ser?
(la url es correcta).

Saludos y gracias!

**Comment by inc0d3** [comment]
Hola, cuál es la URL?

**Comment by cfollin** [comment]
Hola, gracias por contestar!

Cual URL? la que quiero scanear?

Saludos!
________________________________
De: inc0d3 <notifications@github.com>
Enviado: lunes, 21 de diciembre de 2020 16:00
Para: inc0d3/moodlescan <moodlescan@noreply.github.com>
Cc: cfollin <christopher.folin@hotmail.cl>; Author <author@noreply.github.com>
Asunto: Re: [inc0d3/moodlescan] Moodlescan 0.6 (#5)


Hola, cuál es la URL?

**Comment by inc0d3** [comment]
Sí

**Comment by cfollin** [comment]
Cualquiera, probe con varios y con todos me tira error.



Enviado desde Outlook<http://aka.ms/weboutlook>

________________________________
De: inc0d3 <notifications@github.com>
Enviado: martes, 22 de diciembre de 2020 17:44
Para: inc0d3/moodlescan <moodlescan@noreply.github.com>
Cc: cfollin <christopher.folin@hotmail.cl>; Author <author@noreply.github.com>
Asunto: Re: [inc0d3/moodlescan] Moodlescan 0.6 (#5)


Sí

**Comment by inc0d3** [comment]
se crearon pruebas unitarias para probar funcionamiento, está todo OK, dale una mirada. La nueva versión también deja un log con los errores, por si en tu caso persiste, puedas compartir el error.
