### ISSUE TITLE
Error moodlescan

### ISSUE THREAD

**Issue by cfollin** [inc0d3/moodlescan#6]
Hola, aun no he podido usar la herramienta. Ahora me tira el error de la imagen.
Cómo lo puedo solucionar?

Saludos y gracias.
![Error](https://user-images.githubusercontent.com/72315001/104748942-055e1d00-5731-11eb-82c8-d33e849d5ddb.jpeg)

**Comment by mortada-jafar** [comment]
ignore ssl by using  `-k` argument

**Comment by cortantief** [comment]
Or you can add in line 133 in the add_argument method default = False as such:
parser.add_argument('-k', action="store_true", dest="ignore", help="Ignore SSL Certificate", default=False)

**Comment by reboltof** [comment]
Isn't it default=True ?

**Comment by inc0d3** [comment]
The problem is the format in URL, without  "http" or "https" prefix. Now this bug is fixed
