### ISSUE TITLE
Have an issue

### ISSUE THREAD

**Issue by fairy7al3** [inc0d3/moodlescan#9]
Im using kali for 2 days, so i dont understand how to fix it(
![IMG_20220305_215543.jpg](https://user-images.githubusercontent.com/90237212/156899702-6b2fe704-0dd1-4d4f-9d40-877fa058907b.jpg)

**Comment by its0x08** [comment]
Install libssl using the command below and it should work.
```bash
sudo apt-get install libssl-dev 
```
